spring:
    application:
        name: web-ml
    profiles:
        active: local
    datasource:
#        url: jdbc:mysql://webml.cjsggua6auwx.ap-southeast-2.rds.amazonaws.com:3306/webml?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#        username: admin
#        password: 1q2w3e4r!!
#        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:h2:tcp://localhost/~/webml
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                #                show_sql: true
                format_sql: true
                user_sql_comment: true
                default_batch_fetch_size: 10

logging.level:
    org:
        hibernate.SQL: debug

server.servlet.session.timeout: 1800


server:
    servlet:
        session:
            persistent: false